### ISSUE TITLE
Impossible to get weather

### ISSUE THREAD

**Issue by kalon33** [GladysProject/gladys-data#14]
When asking for weather, I get an error and nothing from Gladys:

0|app      | Telegram : Received message on chat ID = 440064144, from = "Nicolas undefined" with content = "Est-ce qu'il pleut demain ?"
0|app      | brain : classify : Identified label weather;get-weather
0|app      | Getting conversation 40988a30-8538-4796-9021-f3627ef0332f, found 1 messages.
0|app      | Brain : classify : Error while executing command in service = weather, label = get-weather
0|app      | Error: NotFound
0|app      |     at /root/gladys/api/core/utils/utils.sqlUnique.js:8:39
0|app      |     at tryCatcher (/root/gladys/node_modules/bluebird/js/release/util.js:16:23)
0|app      |     at Promise._settlePromiseFromHandler (/root/gladys/node_modules/bluebird/js/release/promise.js:512:31)
0|app      |     at Promise._settlePromise (/root/gladys/node_modules/bluebird/js/release/promise.js:569:18)
0|app      |     at Promise._settlePromise0 (/root/gladys/node_modules/bluebird/js/release/promise.js:614:10)
0|app      |     at Promise._settlePromises (/root/gladys/node_modules/bluebird/js/release/promise.js:693:18)
0|app      |     at Promise._fulfill (/root/gladys/node_modules/bluebird/js/release/promise.js:638:18)
0|app      |     at /root/gladys/node_modules/bluebird/js/release/nodeback.js:42:21
0|app      |     at /root/gladys/node_modules/sails-mysql/lib/connections/spawn.js:120:16
0|app      |     at Object.poolfully [as releaseConnection] (/root/gladys/node_modules/sails-mysql/lib/connections/release.js:28:12)
0|app      |     at Query._callback (/root/gladys/node_modules/sails-mysql/lib/connections/spawn.js:105:35)
0|app      |     at Query.Sequence.end (/root/gladys/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
0|app      |     at Query._handleFinalResultPacket (/root/gladys/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Query.js:144:8)
0|app      |     at Query.EofPacket (/root/gladys/node_modules/sails-mysql/node_modules/mysql/lib/protocol/sequences/Query.js:128:8)
0|app      |     at Protocol._parsePacket (/root/gladys/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:280:23)
0|app      |     at Parser.write (/root/gladys/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Parser.js:73:12)
0|app      |     at Protocol.write (/root/gladys/node_modules/sails-mysql/node_modules/mysql/lib/protocol/Protocol.js:39:16)
0|app      |     at Socket.<anonymous> (/root/gladys/node_modules/sails-mysql/node_modules/mysql/lib/Connection.js:96:28)
0|app      |     at emitOne (events.js:115:13)
0|app      |     at Socket.emit (events.js:210:7)
0|app      |     at addChunk (_stream_readable.js:266:12)
0|app      |     at readableAddChunk (_stream_readable.js:253:11)
0|app      |     at Socket.Readable.push (_stream_readable.js:211:10)
0|app      |     at TCP.onread (net.js:585:20)
0|app      | Brain : answer : Answering with label error in language fr-FR
0|app      | Brain : answer : Found 2 possible.
0|app      | Brain : answer : Trying to contact telegram
0|app      | Message sent with success with telegram. Aborting the chain.
0|app      | brain : classify : Answered in 0s, 121.075 ms

**Comment by RyanParsley** [comment]
I have the same issue. I feel like there's a base configuration that isn't covered in the setup. Like, maybe weather needs an address and doesn't get it from the address set as your home? I was expecting the weather widget to be a simple hello world introduction to gladys.

**Comment by Pierre-Gilles** [comment]
You're right it should be simpler to get the weather.

Actually the weather needs your location, so if you haven't been located once, Gladys can't get the weather where you are. We should definitely : 
- Improve logging so you can understand what's going on here
- Create a fallback if the user is not located, and use the house position for example 

Both are in our todo list :)
